# Generated by Django 6.0.3 on 2026-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand_type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('accessory', 'Accessory')])),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
