# Generated by Django 6.0.3 on 2026-03-16 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('just_in', models.BooleanField(null=True)),
                ('free_gift', models.BooleanField(null=True)),
                ('discount', models.BooleanField(null=True)),
                ('discount_percentage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_price', models.FloatField(null=True)),
                ('free_shipping', models.BooleanField(null=True)),
                ('shipping_fee', models.FloatField(null=True)),
                ('in_stock', models.BooleanField(null=True)),
                ('stock_left', models.IntegerField(null=True)),
                ('condition', models.CharField(choices=[('in box', 'In Box'), ('new', 'New'), ('almost new', 'Almost New'), ('uk used', 'UK Used'), ('us used', 'US Used')], max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('gpu', models.CharField(max_length=50, null=True)),
                ('memory', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('screen_size', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
