# Generated by Django 6.0.3 on 2026-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gpu',
            field=models.CharField(default='intel', max_length=50, null=True),
        ),
    ]
