# Generated by Django 6.0.3 on 2026-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_color_remove_product_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
