# Generated by Django 6.0.3 on 2026-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='newest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
